import { afterAll, describe, expect, it } from "vitest";
import { generateTypes, RenderDataError, type RenderReport, Template, verify } from "../src/index.js";
import { ExcelManifest, sumChecks } from "./excel-checks.js";
import { corpusFile, expectPassthrough, HOSTILE_DATES, HOSTILE_NUMBERS, HOSTILE_STRINGS, partText, renderablePart } from "./helpers.js";

const TEMPLATE = corpusFile("transactions", "Transactions-Template.xlsx");
const manifest = new ExcelManifest("transactions");
afterAll(() => manifest.save());

const day = (d: number) => new Date(Date.UTC(2026, 0, d));

interface Txn {
	Merchant?: string | null;
	Date?: Date | null;
	Amount?: number | bigint | null;
}
interface Data {
	Table1?: { Merchant?: string | null; rows: Txn[] }[];
}

function makeGroups(groups: number, perGroup: number): NonNullable<Data["Table1"]> {
	return Array.from({ length: groups }, (_, g) => ({
		Merchant: `Category ${g + 1}`,
		rows: Array.from({ length: perGroup }, (_, i) => ({
			Merchant: `Merchant ${g}-${i}`,
			Date: day(1 + ((g + i) % 28)),
			Amount: Math.round(((g + 1) * 13.37 + i * 1.11) * 100) / 100,
		})),
	}));
}

async function renderWithReport(tpl: Template<Data>, data: Data) {
	let report: RenderReport | undefined;
	const warnings: string[] = [];
	const out = await tpl.render(data, { onReport: (r) => (report = r), onWarning: (w) => warnings.push(w) });
	return { out, report: report as RenderReport, warnings };
}

describe("transactions template (grouped, highlighted, with subtotals and a grand total)", () => {
	it("inspect() infers the grouped shape and field types from the sample rows", async () => {
		const tpl = await Template.load(TEMPLATE);
		const schema = tpl.inspect();
		expect(schema.regions).toHaveLength(1);
		const region = schema.regions[0]!;
		expect(region).toMatchObject({ key: "Table1", kind: "table", sheet: "Transactions", sampleRange: "A5:C11", fixedRows: ["A11:C11"] });
		expect(region.shape).toEqual({
			kind: "groups",
			fields: [{ name: "Merchant", type: "string", samples: ["Groceries", "Shopping"] }],
			childKey: "rows",
			child: {
				kind: "rows",
				fields: [
					{ name: "Merchant", type: "string" },
					{ name: "Date", type: "date" },
					{ name: "Amount", type: "number" },
				],
			},
		});
		expect(generateTypes(schema, "TransactionsData")).toMatchInlineSnapshot(`
			"// Generated by excel-graft from the template's structure. Regenerate when the workbook changes.
			import type { CellValue, FormulaValue } from "excel-graft";

			export interface TransactionsData {
				/** Table "Table1" on sheet "Transactions" (sample rows A5:C11). */
				Table1?: {
					Merchant?: "Groceries" | "Shopping" | (string & {}) | string | null | FormulaValue;
					rows: {
						Merchant?: string | null | FormulaValue;
						Date?: Date | null | FormulaValue;
						Amount?: number | bigint | null | FormulaValue;
					}[];
				}[];
			}
			"
		`);
	});

	it("rewrites subtotals and the grand total to cover the inserted rows", async () => {
		const tpl = await Template.load<Data>(TEMPLATE);
		const data: Data = {
			Table1: [
				{ Merchant: "Groceries", rows: [{ Merchant: "HEB", Date: day(3), Amount: 12.5 }, { Merchant: "Kroger", Date: day(4), Amount: 7 }, { Merchant: "Aldi", Date: day(5), Amount: 1 }] },
				{ Merchant: "Fuel", rows: [{ Merchant: "Shell", Date: day(6), Amount: 40 }] },
				{ Merchant: "Empty category", rows: [] },
			],
		};
		const { out, report } = await renderWithReport(tpl, data);
		expect(verify(out)).toEqual([]);
		const sheet = partText(out, "xl/worksheets/sheet1.xml");
		expect(sheet).toContain('<c r="C5" s="4"><f>SUM(C6:C8)</f></c>');
		expect(sheet).toContain('<c r="C9" s="4"><f>SUM(C10:C10)</f></c>');
		expect(sheet).toContain('<c r="C11" s="4"><f>SUM(C12:C12)</f></c>');
		expect(sheet).toContain('<c r="C13" s="7"><f>SUM(C5,C9,C11)</f></c>');
		// Highlighted group rows keep their row and cell styles.
		expect(sheet).toMatch(/<row r="9" [^>]*s="1" customFormat="1"/);
		expect(sheet).toContain('<c r="A9" s="1" t="inlineStr"><is><t>Fuel</t></is></c>');
		// The date and currency formats come from the template row.
		expect(sheet).toContain('<c r="B6" s="2"><v>46025</v></c>');
		const table = partText(out, "xl/tables/table1.xml");
		expect(table).toContain('ref="A4:C13"');
		expect(table).toContain('<autoFilter ref="A4:C13"');
		// calcChain is gone; Excel recalculates on open.
		expect(partText(out, "xl/workbook.xml")).toContain('fullCalcOnLoad="1"');
		const changed = expectPassthrough(TEMPLATE, out, renderablePart);
		expect(changed.sort()).toEqual(["[Content_Types].xml", "xl/_rels/workbook.xml.rels", "xl/tables/table1.xml", "xl/workbook.xml", "xl/worksheets/sheet1.xml"]);
		const cells = sumChecks(tpl.inspect(), report, out);
		expect(cells.map((c) => [c.cell, c.value])).toEqual([
			["C5", 20.5],
			["C9", 40],
			["C11", 0],
			["C13", 60.5],
		]);
		manifest.add("transactions/grouped-small.xlsx", out, { cells, tables: [{ name: "Table1", dataRows: 9 }] });
	});

	it("a single group isn't counted twice by a grand total that listed two sample groups", async () => {
		// Found by the Excel harness: SUM(C5,C8) over one output group became SUM(C5,C5).
		const tpl = await Template.load<Data>(TEMPLATE);
		const { out, report } = await renderWithReport(tpl, { Table1: [{ Merchant: "Only", rows: [{ Amount: 10 }, { Amount: 5 }] }] });
		expect(partText(out, "xl/worksheets/sheet1.xml")).toContain('<c r="C8" s="7"><f>SUM(C5)</f></c>');
		const cells = sumChecks(tpl.inspect(), report, out);
		expect(cells.map((c) => [c.cell, c.value])).toEqual([
			["C5", 15],
			["C8", 15],
		]);
		manifest.add("transactions/single-group.xlsx", out, { cells, tables: [{ name: "Table1", dataRows: 4 }] });
	});

	it("an empty data array still leaves a valid table with one blank group", async () => {
		const tpl = await Template.load<Data>(TEMPLATE);
		const { out } = await renderWithReport(tpl, { Table1: [] });
		expect(verify(out)).toEqual([]);
		const table = partText(out, "xl/tables/table1.xml");
		expect(table).toContain('ref="A4:C7"');
		manifest.add("transactions/empty.xlsx", out, { cells: [{ sheet: "Transactions", cell: "C7", value: 0, note: "grand total of nothing" }], tables: [{ name: "Table1", dataRows: 3 }] });
	});

	it("renders 100,000 rows in 1,000 groups quickly and correctly", async () => {
		const tpl = await Template.load<Data>(TEMPLATE);
		const data = { Table1: makeGroups(1000, 99) };
		const started = performance.now();
		const { out, report } = await renderWithReport(tpl, data);
		const ms = performance.now() - started;
		expect(ms).toBeLessThan(15_000);
		expect(verify(out)).toEqual([]);
		const region = report.regions[0]!;
		expect(region.lastRow - region.firstRow + 1).toBe(1000 * 100 + 1);
		const sheet = partText(out, "xl/worksheets/sheet1.xml");
		// The grand total lists 1,000 group rows, so it's wrapped as one union argument (Excel allows 255 arguments).
		const grand = /<c r="C100005" s="7"><f>SUM\(\((C5,C105,.*)\)\)<\/f><\/c>/.exec(sheet);
		expect(grand).not.toBeNull();
		expect(grand![1]!.split(",")).toHaveLength(1000);
		const cells = sumChecks(tpl.inspect(), report, out);
		manifest.add("transactions/grouped-100k.xlsx", out, {
			cells: [cells[0]!, cells[cells.length - 2]!, cells[cells.length - 1]!],
			tables: [{ name: "Table1", dataRows: 100_001 }],
		});
	}, 60_000);

	it("survives hostile values: control characters, huge text, NaN, bigints, odd dates", async () => {
		const tpl = await Template.load<Data>(TEMPLATE);
		const rows: Txn[] = [];
		const n = Math.max(HOSTILE_STRINGS.length, HOSTILE_NUMBERS.length, HOSTILE_DATES.length);
		for (let i = 0; i < n; i++) {
			rows.push({
				Merchant: HOSTILE_STRINGS[i % HOSTILE_STRINGS.length] as string,
				Date: HOSTILE_DATES[i % HOSTILE_DATES.length] as Date,
				Amount: HOSTILE_NUMBERS[i % HOSTILE_NUMBERS.length] as number,
			});
		}
		const { out } = await renderWithReport(tpl, { Table1: [{ Merchant: HOSTILE_STRINGS[2]!, rows }, { Merchant: null, rows: [{}] }] });
		expect(verify(out)).toEqual([]);
		const sheet = partText(out, "xl/worksheets/sheet1.xml");
		expect(sheet).toContain("_x0001__x0002__x0008__x000B__x000C__x001F_");
		expect(sheet).toContain("_x005F_x0041_ literal escape");
		expect(sheet).toContain("<t>=1+1 looks like a formula</t>");
		expect(sheet).toContain("<v>#NUM!</v>");
		manifest.add("transactions/hostile.xlsx", out, { cells: [], tables: [{ name: "Table1", dataRows: rows.length + 4 }] });
	});

	it("fails loudly on a misspelled key, bad shapes, and (optionally) missing or unknown fields", async () => {
		const tpl = await Template.load<Record<string, unknown>>(TEMPLATE);
		await expect(tpl.render({ Tabel1: [] })).rejects.toThrow(/"Tabel1" doesn't match any table.*Known keys: Table1/);
		await expect(tpl.render({ Table1: {} })).rejects.toThrow(RenderDataError);
		await expect(tpl.render({ Table1: [{ Merchant: "x", rows: {} }] })).rejects.toThrow(/rows must be an array/);
		await expect(tpl.render({ Table1: [{ Merchant: "x", rows: [{ Amount: { nested: 1 } }] }] })).rejects.toThrow(/is an object/);
		await expect(tpl.render({ Table1: [{ Merchant: "x", rows: [{ Merchant: "y" }] }] }, { onMissing: "error" })).rejects.toThrow(/missing value/);
		await expect(tpl.render({ Table1: [{ Merchant: "x", rows: [{ Amont: 1 }] }] }, { strict: true })).rejects.toThrow(/Amont doesn't match any column/);
	});

	it("one Template renders many times, concurrently, without cross-talk", async () => {
		const tpl = await Template.load<Data>(TEMPLATE);
		const [a, b, a2] = await Promise.all([tpl.render({ Table1: makeGroups(3, 2) }), tpl.render({ Table1: makeGroups(5, 5) }), tpl.render({ Table1: makeGroups(3, 2) })]);
		expect(Buffer.from(a2!).equals(Buffer.from(a!))).toBe(true);
		expect(Buffer.from(a!).equals(Buffer.from(b!))).toBe(false);
		// The template itself is untouched.
		expect(Buffer.from(await tpl.toBuffer()).length).toBeGreaterThan(0);
		expectPassthrough(TEMPLATE, await tpl.toBuffer(), () => false);
	});

	it("leaves regions without data untouched", async () => {
		const tpl = await Template.load<Data>(TEMPLATE);
		const out = await tpl.render({});
		expectPassthrough(TEMPLATE, out, () => false);
	});
});
