import type { FieldSchema, ShapeSchema, TemplateSchema } from "./template.js";

const IDENT_RE = /^[A-Za-z_$][\w$]*$/;

/** Fields accept their sample's type (plus null for an empty cell, and a formula object). */
const FIELD_TS: Record<FieldSchema["type"], string> = {
	string: "string | null | FormulaValue",
	number: "number | bigint | null | FormulaValue",
	date: "Date | null | FormulaValue",
	boolean: "boolean | null | FormulaValue",
	unknown: "CellValue",
};

function key(name: string): string {
	return IDENT_RE.test(name) ? name : JSON.stringify(name);
}

function shapeType(shape: ShapeSchema, indent: string): string {
	const inner = `${indent}\t`;
	const fields = shape.fields.map((f) => {
		// Known sample labels become autocomplete hints without rejecting other labels.
		const hint = f.samples?.length ? `${[...new Set(f.samples)].map((s) => JSON.stringify(s)).join(" | ")} | (string & {}) | ` : "";
		return `${inner}${key(f.name)}?: ${hint}${FIELD_TS[f.type]};`;
	});
	if (shape.kind === "groups") fields.push(`${inner}${key(shape.childKey)}: ${shapeType(shape.child, inner)}[];`);
	return `{\n${fields.join("\n")}\n${indent}}`;
}

/**
 * Generates a TypeScript interface for a template's data, so a renamed
 * column or a new grouping level becomes a compile error in the API that
 * fills it.
 */
export function generateTypes(schema: TemplateSchema, typeName = "TemplateData", importFrom = "excel-graft"): string {
	const lines: string[] = [
		"// Generated by excel-graft from the template's structure. Regenerate when the workbook changes.",
		`import type { CellValue, FormulaValue } from ${JSON.stringify(importFrom)};`,
		"",
		`export interface ${typeName} {`,
	];
	for (const r of schema.regions) {
		const what = r.kind === "table" ? `Table "${r.key}"` : `Named range "${r.key}"`;
		lines.push(`\t/** ${what} on sheet "${r.sheet}" (sample rows ${r.sampleRange}). */`);
		lines.push(`\t${key(r.key)}?: ${shapeType(r.shape, "\t")}[];`);
	}
	const scalarRoots = new Map<string, Set<string>>();
	for (const s of schema.scalars) {
		const [root, ...rest] = s.key.split(".");
		if (root === undefined) continue;
		const set = scalarRoots.get(root) ?? new Set<string>();
		if (rest.length > 0) set.add(rest.join("."));
		scalarRoots.set(root, set);
	}
	for (const [root, subs] of scalarRoots) {
		if (schema.regions.some((r) => r.key === root)) continue;
		if (subs.size === 0) {
			lines.push(`\t${key(root)}?: CellValue;`);
		} else {
			lines.push(`\t${key(root)}?: ${nestedType([...subs], "\t")};`);
		}
	}
	lines.push("}", "");
	return lines.join("\n");
}

function nestedType(paths: string[], indent: string): string {
	const groups = new Map<string, string[]>();
	for (const p of paths) {
		const [head, ...rest] = p.split(".");
		if (head === undefined) continue;
		const list = groups.get(head) ?? [];
		if (rest.length > 0) list.push(rest.join("."));
		groups.set(head, list);
	}
	const inner = `${indent}\t`;
	const fields = [...groups].map(([k, rest]) => `${inner}${key(k)}?: ${rest.length > 0 ? nestedType(rest, inner) : "CellValue"};`);
	return `{\n${fields.join("\n")}\n${indent}}`;
}
